apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: exam2025
        image: gcr.io/examenfinal-458623/exam2025:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: GCP_BUCKET_NAME
            value: REPLACE_BUCKET_NAME
        livenessProbe:
          periodSeconds: 2
          httpGet:
            path: /probe
            port: 5000


